name: Build latex files
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build pdfs
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
      - name: Publish pdfs
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: "*.pdf"
      - name: "Enable submodules"
        run: |
           git lfs track "*.pdf"
           git add .gitattributes
      - name: Commit new pdfs
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.pdf"
          committer_name: Pdf builder
          committer_email: noemail@example.com
          default_author: user_info
          message: '[no ci] Add pdfs'
          pathspec_error_handling: exitImmediately
          push: true
